# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tryStreams' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tryStreams
     #pod 'AWSiOSSDKv2'	
     pod 'AWSAPIGateway'
     pod 'AWSAuth'
     pod 'AWSAuthCore'
     pod 'AWSCognito'
     pod 'AWSCognitoAuth'
     pod 'AWSCognitoIdentityProvider'
     pod 'AWSCognitoSync'
     pod 'AWSKinesis'
     pod 'AWSKinesisVideo'
     pod 'AWSCore'
     pod 'AWSKMS'
end
