source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

use_frameworks!

target 'HMWebRTC_Example' do

    pod 'HMWebRTC', :path => '../'

    target 'HMWebRTC_Tests' do
    inherit! :search_paths

    end
end
